import type { GalleryItem } from '@/types/gallery';

export const galleryItems: GalleryItem[] = [
  {
    id: 1,
    date: 'Sabtu, 15 Maret 2025',
    title: 'Welcome Party HMTC Suar Peradaban 2025',
    image: '/gallery/Welpar2025.png',
    link: 'https://drive.google.com/drive/folders/1AmY8SkOeqTYtT6uA2iDm1i62vhpFmXfz?usp=drive_link',
    width: 585,
    height: 390,
  },
  {
    id: 2,
    date: 'Minggu, 23 Maret 2025',
    title: 'Berbakti 2025',
    image: '/gallery/Berbakti2025.png',
    link: 'https://drive.google.com/drive/folders/1s9Hrz5W03olCzESZNrXc4Vzo2z-u4UnR?usp=drive_link',
    width: 540,
    height: 360,
  },
  {
    id: 3,
    date: 'Sabtu, 12 April 2025',
    title: 'Wisuda Trailer 2025',
    image: '/gallery/SW131Trailer.png',
    link: 'https://drive.google.com/drive/folders/1R5o9BkofLNMsTPOSQ6kXNsxROPGrovMc?usp=drive_link',
    width: 536,
    height: 357,
  },
  {
    id: 4,
    date: 'Minggu, 13 Maret 2025',
    title: 'Wisuda-131 2025',
    image: '/gallery/SW131.png',
    link: 'https://drive.google.com/drive/folders/1wtYFpykEkyBb9uuPIMeO0nv3rrh7uo1a?usp=drive_link',
    width: 540,
    height: 360,
  },
  {
    id: 5,
    date: 'Minggu, 16 Mei 2025',
    title: 'Reveal Kabinet 2025',
    image: '/gallery/revealKabinet.png',
    link: 'https://drive.google.com/drive/folders/1rQZvBYfEGWTZ2pC1v8XL8UTXHPRfDGv4?usp=drive_link',
    width: 640,
    height: 960,
  },
  {
    id: 6,
    date: 'Senin, 17 Mei 2025',
    title: 'Incremental HMTC 2025',
    image: '/gallery/incremental.jpg',
    link: 'https://drive.google.com/drive/folders/1MjRj3XW6tY0KaVI8BaHxJeU6A4rgAnEg?usp=drive_link',
    width: 640,
    height: 960,
  },
  {
    id: 7,
    date: 'Sabtu, 24 Mei 2025',
    title: 'TConference 2025',
    image: '/gallery/tConference.jpg',
    link: 'https://drive.google.com/drive/folders/1tfpjLBcLiS4ZQuYl_HRSQ7htZuuHdcz9?usp=drive_link',
    width: 640,
    height: 960,
  },
  {
    id: 8,
    date: 'Sabtu, 15 Maret 2025',
    title: 'Preambule Nawasena 2025',
    image: '/gallery/preAmbule.jpg',
    link: 'https://drive.google.com/drive/folders/1qOdxHA4yGBnw4dRclBO8WAU18J-tFtrc?usp=drive_link',
    width: 640,
    height: 960,
  },
  {
    id: 9,
    date: 'Minggu, 25 Mei 2025',
    title: 'HMTC x HMM',
    image: '/gallery/hmtcXhmm.jpg',
    link: 'https://drive.google.com/drive/folders/1KL5AygXUY9AyF3gjn9ILC3yu2TdsN36e?usp=drive_link',
    width: 640,
    height: 960,
  },
  {
    id: 10,
    date: 'Jumat, 21 Maret 2025',
    title: 'Pembukaan Nawasena 2025',
    image: '/gallery/pembukaanNawasena.jpg',
    link: 'https://drive.google.com/drive/folders/1Oz5ZnPMsDoLf2P3hLvVg1J-QQe-LX_2B?usp=sharing',
    width: 397,
    height: 595,
  },
  {
    id: 11,
    date: 'Minggu, 1 Juni 2025',
    title: 'HMTC x HMTI Unair',
    image: '/gallery/hmtchmti.jpg',
    link: 'https://drive.google.com/drive/folders/1nM61dEfcR6SXTEnFTHZPDLtD7l4SNhyP?usp=sharing',
    width: 400,
    height: 600,
  },
  {
    id: 12,
    date: 'Minggu, 1 Juni 2025',
    title: 'Futsal HMTC vs HIMATEKTRO',
    image: '/gallery/futsalTCELEKTRO.jpg',
    link: 'https://drive.google.com/drive/folders/1-xWYEpeDIgyoxqun1VB7O5-KeiRN22oi?usp=sharing',
    width: 400,
    height: 600,
  },
  {
    id: 13,
    date: 'Sabtu, 21 Juni 2025',
    title: 'TCatalyst 1',
    image: '/gallery/TCatalyst1.jpg',
    link: 'https://drive.google.com/drive/folders/1EKggy7P-6ydYgljsk_ZRs5Z-Ez_XfzWP?usp=drive_link',
    width: 400,
    height: 600,
  },
  {
    id: 14,
    date: 'Jumat, 20 Juni 2025',
    title: 'LKMM TD',
    image: '/gallery/LKMMTD.jpg',
    link: 'https://drive.google.com/drive/folders/1awNC_OhPlpAovkhs5zPSopJ_Fw0L8WwP?usp=drive_link',
    width: 600,
    height: 400,
  },
  {
    id: 15,
    date: 'Jumat, 13 Juni 2025',
    title: 'Tutor EAS',
    image: '/gallery/TutorEAS.jpg',
    link: 'https://drive.google.com/drive/folders/1oi5gHWyj8J_H6nos7agR4i_fEmGSkInr?usp=drive_link',
    width: 400,
    height: 600,
  },
  {
    id: 16,
    date: 'Rabu, 23 Juli 2025',
    title: 'HGTS 2025',
    image: '/gallery/HGTS2025.jpg',
    link: 'https://drive.google.com/drive/folders/1ay4aaDzR3xS2da-ytGg6yzRz9EimZsFQ?usp=sharing',
    width: 400,
    height: 600,
  },
  {
    id: 17,
    date: 'Senin, 4 Agustus 2025',
    title: 'OKKBK 2025',
    image: '/gallery/OKKBK_2025.jpg',
    link: 'https://drive.google.com/drive/folders/1ybZxITVSKN2LyzcoR59CfUFn7VD3bSKh?usp=drive_link',
    width: 600,
    height: 400,
  },
  {
    id: 18,
    date: 'Jumat, 8 Agustus 2025',
    title: 'Maba Fun Day',
    image: '/gallery/MABA_FUN_DAY.jpg',
    link: 'https://drive.google.com/drive/folders/1bCJJPb3rp_jPoYcWlG8uzOMTksCdOcyJ?usp=drive_link',
    width: 600,
    height: 400,
  },
  {
    id: 19,
    date: 'Sabtu, 23 Agustus 2025',
    title: 'HMTC x HIMASTHAPATI',
    image: '/gallery/HMTC_HIMASTHAPATI.jpg',
    link: 'https://drive.google.com/drive/folders/1b4WWuAihpH-tSqN7J15dHU69j2v44qcb?usp=drive_link',
    width: 600,
    height: 400,
  },
  {
    id: 20,
    date: 'Kamis, 28 Agustus 2025',
    title: 'TConference 29 Agustus',
    image: '/gallery/TCONFERENCE_2.jpg',
    link: 'https://drive.google.com/drive/folders/1FWhx5HLQ96sTVrr67NW48ogGc7Qru_t4?usp=drive_link',
    width: 600,
    height: 400,
  },
  {
    id: 21,
    date: 'Kamis, 28 Agustus 2025',
    title: 'Forum 1 Nawasena',
    image: '/gallery/FORUM_1_NAWASENA.jpg',
    link: 'https://drive.google.com/drive/folders/18nukN3hSqyaqyX_uG01ORIEy1PkKxIB9?usp=drive_link',
    width: 600,
    height: 400,
  },
  {
    id: 22,
    date: 'Jumat, 5 September 2025',
    title: 'Safari Lab',
    image: '/gallery/SAFARI_LAB.jpg',
    link: 'https://drive.google.com/drive/folders/16l31THAY5uIENZPZT1nifL8Rusa1t_dd?usp=drive_link',
    width: 600,
    height: 400,
  },
  {
    id: 23,
    date: 'Minggu, 7 September 2025',
    title: 'Comvis Microsoft Huawei',
    image: '/gallery/COMVIS.jpg',
    link: 'https://drive.google.com/drive/folders/1g151f-l4WpVJCD3CTcSGRtF8qxp04Jgj?usp=drive_link',
    width: 600,
    height: 400,
  },
  {
    id: 24,
    date: 'Minggu, 14 September 2025',
    title: 'Basic Media Schooling (BMS)',
    image: '/gallery/BMS.jpg',
    link: 'https://drive.google.com/drive/folders/1Jo4JAVToKYBU07TR8c0M-Dzqci-QNbWL?usp=drive_link',
    width: 600,
    height: 400,
  },
  {
    id: 25,
    date: 'Sabtu, 20 September 2025',
    title: 'SW 132',
    image: '/gallery/SW132.jpg',
    link: 'https://drive.google.com/drive/folders/1BqVG3-YIjzDQyu2H60m4zdFEXtchSJB5?usp=drive_link',
    width: 600,
    height: 400,
  },
  {
    id: 26,
    date: 'Sabtu, 01 November 2025',
    title: 'Pengangkatan C28',
    image: '/gallery/c28.jpg',
    link: 'https://drive.google.com/drive/folders/1rEv_qslsDyAzfnuyIHCqk5wY_yBQKqTB',
    width: 600,
    height: 400,
  },
  {
    id: 27,
    date: 'Minggu, 02 November 2025',
    title: 'PKTI TD',
    image: '/gallery/pktiTd.jpg',
    link: 'https://drive.google.com/drive/folders/1XWaXGgFV6weNlx74ahAqZ65DvB9yvSR2?usp=sharing',
    width: 600,
    height: 400,
  },
  {
    id: 28,
    date: 'Minggu, 09 November 2025',
    title: 'Alumni Akbar TC',
    image: '/gallery/alumniAkbarTC.jpg',
    link: 'https://drive.google.com/drive/folders/1m8hr9rYE3EMrIJ8j1uUfdCFEzbNt10i7?usp=sharing',
    width: 600,
    height: 400,
  },
  {
    id: 29,
    date: 'Minggu, 09 November 2025',
    title: 'Welpar magang HMTC',
    image: '/gallery/welparMagangHMTC.jpg',
    link: 'https://drive.google.com/drive/folders/1NWDDJwUxttrsEkaaXT_-JhxibKhXc9Bq?usp=sharing',
    width: 600,
    height: 400,
  },
  {
    id: 30,
    date: 'Jumat, 21 November 2025',
    title: 'HMTC Next Gen',
    image: '/gallery/hmtcNextGen.jpg',
    link: 'https://drive.google.com/drive/folders/159N_AaDYZDov6AIlV3_dxGiJV0bmHqA7?usp=sharing',
    width: 600,
    height: 400,
  },
  {
    id: 31,
    date: 'Minggu, 23 November 2025',
    title: 'PKTI - TC Cup',
    image: '/gallery/tcCup.JPG',
    link: 'https://drive.google.com/drive/folders/18RofQxAGvn6Zg8FGOynWTmPRPmHCjeMR?usp=sharing',
    width: 600,
    height: 400,
  },
];
